name: Unit tests
on: push

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b
        with:
          runtime: node
          cache: true
          working-directory: ./unit-tests
      - run: pnpm test
        working-directory: ./unit-tests
